### ISSUE TITLE
Similar package based on sPOT 

### ISSUE THREAD

**Issue by mloubout** [JuliaLinearAlgebra/LinearMaps.jl#168]
Hello

We just ran into this package and it looks like there is quite the overlap (and differences) with a package we have been developing since julia v0.5. Our research group I(SLIM @ gatech, https://github.com/slimgroup)  was heavily involved with `SPOT` that you mention in the documentation, including `pSPOT` a distributed extension.

Our package is called [JOLI.jl](https://github.com/slimgroup/JOLI.jl) and we think there is room for collaboration/combination to maybe get the best of both worlds. Some design principles are slightly different and may need some rethink but it may be beneficial in the long term.

cheers

@henryk-modzelewski, @ziyiyin97 if you have some more to say.

**Comment by dkarrasch** [comment]
Thanks for reaching out. I see the documentation is overwhelmingly extensive. Do you have some ideas where collaboration/consolidation could be beneficial?

**Comment by Jutho** [comment]
Thanks indeed from my side as well; it is indeed surprising that we did not learn from each other's existence earlier. Just as a historical aside, development of LinearMaps.jl actually started in 2014 using Julia v0.3: https://github.com/JuliaLinearAlgebra/LinearMaps.jl/tree/v0.0.1

**Comment by mloubout** [comment]
Thanks for getting back. And nice to meet you of course.

>  actually started in 2014 

Wow we completely missed that, would have been a good idea to notice then and make things more uniform/compatible.

>Do you have some ideas where collaboration/consolidation could be beneficial?

Top of my head, not really. I am still trying to wrap my head around similarities and differences to see what a good starting point would be and which parts could be beneficial to each other.  If the two packages turn out to be too different then we'll see I just thought it could be a good opportunity to look into it.

**Comment by mloubout** [comment]
Would also like to say that I really like the way you handle composition of linear maps, seems very flexible and extendable to new Maps.
