### ISSUE TITLE
Support for arrays in addition to tuples in LinearCombination

### ISSUE THREAD

**Issue by oschulz** [JuliaLinearAlgebra/LinearMaps.jl#169]
We use LinearMaps extensively in [MGVI.jl](https://github.com/bat/MGVI.jl). We're adding support for Newton-CG-optimization now which needs means of linear maps. The number of maps in the mean/sum is not fixed though, so we'd like to use an array of maps instead of a tuple in `LinearCombination`. Would a pull request to extend `LinearCombination` that way be welcome?

**Comment by oschulz** [comment]
>  because these tuples are all lazy, i.e., adding another map to an existing LinearCombination forms a new tuple (of pointers to the maps) of lenght one bigger than before

Yes, the problem is the load on the compiler, with new data types created all the time for tuples of different length (and n can be  hundreds of even thousands in our use case). Mean itself works fine indeed already.

> Statistics.mean(A::LinearCombination) = mean(A.maps)

Yes, forgot to mention, I would like to specialize `mean` and `sum`. And from what I can see `LinearCombination` should work just fine if we allow `As<:Union{LinearMapTuple,AbstractArray{<:LinearMap}` or similar.

Just wanted to check with you before preparing a PR.

**Comment by oschulz** [comment]
> I'm glad to hear LinearMaps.jl is used.

It's awesome! We found it to be a very powerful abstraction. We use it for lazy Jacobians too, with both left- and right-multiplication (backed by ForwardDiff and Zygote, by default).

**Comment by oschulz** [comment]
CC MGVI devs @apmypb, @jknollm and @vindex10

**Comment by dkarrasch** [comment]
Before you start with your own PR, check out #84. It does a few more things (to block concatenation), but it already has the `LinearCombination` extension that you want, including some adoption of the `mul!` machinery. So you could play with it and see how things work.

**Comment by oschulz** [comment]
Thanks, will do! Should I just base a PR on top of #84?

**Comment by dkarrasch** [comment]
That was just a suggestion for a quick start. It's not important which way you go. #84 has more things that we might keep for when there is actual interest in it.

**Comment by oschulz** [comment]
Ok, I'll start with `LinearCombination` and specialized `sum` then.
