### ISSUE TITLE
AD support

### ISSUE THREAD

**Issue by mloubout** [JuliaLinearAlgebra/LinearMaps.jl#176]
Is there a plan to support (partial) AD for Flux for example? Adding `ChainRulesCore` rules for `A*x` should be fairly easy and would allow using LinearMaps easily in ML workflows (considering A non-differentiable since it's a matrix-free operator).

Something similar to:

https://github.com/slimgroup/JOLI.jl/pull/32

**Comment by dkarrasch** [comment]
I believe we had an issue about it, but I can't seem to find it. There is no such plan (at least on my end), but if that is a useful feature we'd be happy to accept PRs. As of now, for me this is unfamiliar ground. Which dependencies would this require?

**Comment by mloubout** [comment]
Well there is two ways to go about it, through `Requires.jl` which would mean no additional dependency, or adding ChainRulesCore which is a very small package with only 2 minor dependencies. I don't mind opening a PR would probably just be a 5-10 lines additon
