### ISSUE TITLE
Unnecessary temp allocation in `mul!` due to `MulStyle(::ScaledMap) == ThreeArg()`

### ISSUE THREAD

**Issue by danielwe** [JuliaLinearAlgebra/LinearMaps.jl#178]
Hi, I'm noticing a temp allocation that should be unnecessary when using `mul!` with a LinearCombination containing one or more ScaledMaps. I'm just beginning to wrap my head around the dispatch behind the scenes here, but simply defining `MulStyle(::ScaledMap) = FiveArg()` gets rid of the allocation, seemingly without any adverse effects, at least for scaled WrappedMaps:

```julia
julia> using BenchmarkTools, LinearAlgebra, LinearMaps

julia> N = 100;

julia> A = 0.6 * LinearMap(randn(N, N)) + 0.4 * LinearMap(randn(N, N));

julia> x = randn(N); y1, y2 = similar(x), similar(x);

julia> @btime mul!($y1, $A, $x);
  2.128 μs (1 allocation: 896 bytes)

julia> LinearMaps.MulStyle(::LinearMaps.ScaledMap) = LinearMaps.FiveArg();

julia> @btime mul!($y2, $A, $x);
  1.998 μs (0 allocations: 0 bytes)

julia> y1 ≈ y2
true
```

It makes sense: with five-arg `mul!` it's straightforward to fold the scaling into the `α` argument. Could this be implemented in the package, or is there a reason it shouldn't?

**Comment by dkarrasch** [comment]
This is pure oversight. Thanks for the report! The better solution is

```julia
MulStyle(A::ScaledMap) = MulStyle(A.lmap)
```

because that will make sure that when the scaled map is `ThreeArg`, you only have one allocation in a linear combination. I'll take care of it.
