### ISSUE TITLE
`vcat` type piracy breaks Manifolds.jl on Julia 1.10

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaLinearAlgebra/LinearMaps.jl#214]
As far as I can see `LinearMaps.jl` commits type piracy with `vcat` that used to work fine with Julia up to 1.9 but on Julia 1.10-beta2 it fails:
```julia
  MethodError: no method matching /(::Adjoint{Float64, Matrix{Float64}}, ::LinearMaps.TransposeMap{Float64, LinearMaps.BlockMap{Float64, Tuple{LinearMaps.UniformScalingMap{Bool}, LinearMaps.WrappedMap{Float64, Matrix{Float64}}, LinearMaps.WrappedMap{Float64, Matrix{Float64}}, LinearMaps.UniformScalingMap{Bool}}, Tuple{Int64, Int64}}})
```
see here: https://github.com/JuliaManifolds/Manifolds.jl/actions/runs/6119202115/job/16608674048?pr=648 .

**Comment by dkarrasch** [comment]
Well, it is innocently pushed to commit type piracy. 😄 This is already taken care of by https://github.com/JuliaLang/julia/pull/51132 and #211.

**Comment by mateuszbaran** [comment]
I see, OK, I will wait then until it's fixed.
