### ISSUE TITLE
Multiplication of kronecker products is reversed

### ISSUE THREAD

**Issue by apmypb** [JuliaLinearAlgebra/LinearMaps.jl#230]
It seems that the product $(A_1 \otimes B_1) \cdot \dots\cdot (A_n \otimes B_n)$ is falsely computed as
$(A_n\cdot\dots\cdot A_1) \otimes (B_n\cdot\dots\cdot B_1)$ and **not** like $(A_1\cdot\dots\cdot A_n) \otimes (B_1\cdot\dots\cdot B_n)$ (the order of maps reversed)
One can check the following minimal working example:
```
using LinearAlgebra
using LinearMaps

A = [0 1; 0 0]
B = [0 0; 1 0]
J = LinearMap(I, 1)
Matrix(kron(J, A*B)) == Matrix(kron(J, A) * kron(J, B)) # should be true
```
Applying `reverse()` on the tuples before the product should do the trick https://github.com/JuliaLinearAlgebra/LinearMaps.jl/blob/ee91b4f119e036aa403e3fb0d7c9094e51f46f70/src/kronecker.jl#L275

**Comment by dkarrasch** [comment]
Thanks for catching this! It had a test, which used the same linear maps, so didn't see the missing `reverse`. :facepalm:
